version: '3.8'

services:
  mysql1:
    image: mysql:8.0
    container_name: mysql1
    hostname: mysql1
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
      MYSQL_DATABASE: appdb
    volumes:
      - ./mysql/mysql1.cnf:/etc/mysql/conf.d/custom.cnf:ro
    command: --server-id=1 --gtid-mode=ON --enforce-gtid-consistency=true --binlog_transaction_dependency_tracking=WRITESET
    restart: always

  mysql2:
    image: mysql:8.0
    container_name: mysql2
    hostname: mysql2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
      MYSQL_DATABASE: appdb
    volumes:
      - ./mysql/mysql2.cnf:/etc/mysql/conf.d/custom.cnf:ro
    command: --server-id=2 --gtid-mode=ON --enforce-gtid-consistency=true --binlog_transaction_dependency_tracking=WRITESET
    restart: always

  mysql3:
    image: mysql:8.0
    container_name: mysql3
    hostname: mysql3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
      MYSQL_DATABASE: appdb
    volumes:
      - ./mysql/mysql3.cnf:/etc/mysql/conf.d/custom.cnf:ro
    command: --server-id=3 --gtid-mode=ON --enforce-gtid-consistency=true --binlog_transaction_dependency_tracking=WRITESET
    restart: always

  mysql-shell:
    build: ./shell
    container_name: mysql-shell
    depends_on:
      - mysql1
      - mysql2
      - mysql3
    volumes:
      - ./shell/init-cluster.js:/init-cluster.js
    # entrypoint: >
    #   bash -c "
    #   sleep 30 &&
    #   mysqlsh --uri root:root@mysql1:3306 --file /init-cluster.js
    #   "
    entrypoint: >
      bash -c "
      tail -f /dev/null
      "

  mysql-router:
    image: mysql/mysql-router:8.0
    container_name: mysql-router
    depends_on:
      - mysql1
      - mysql2
      - mysql3
      - mysql-shell
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: mysql1
  #   entrypoint: >
  #     bash -c "
  #       sleep 120 &&
  #       mysqlrouter --bootstrap root:root@mysql1:3306 --directory /usr/local/mysqlrouter --user=mysqlrouter --force &&
  #       mysqlrouter -c /usr/local/mysqlrouter/mysqlrouter.conf
  #     "
    entrypoint: >
      bash -c "
      tail -f /dev/null
      "
    # volumes:
    # - ./router-data:/usr/local/mysqlrouter
    ports:
      - "6446:6446"

  app:
    build: ./app
    depends_on:
      - mysql-router
    environment:
      DB_HOST: mysql-router
      DB_PORT: 6446
      DB_USER: root
      DB_PASS: root
      DB_NAME: appdb

    entrypoint: >
      bash -c "
      tail -f /dev/null
      "