global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mysql-exporter'
    static_configs:
      - targets: 
        - 'host.docker.internal:9104'  # mysql1-exporter
        - 'host.docker.internal:9105'  # mysql2-exporter
        - 'host.docker.internal:9106'  # mysql3-exporter
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 10s