version: '3.8'

services:
  mysql3:
    image: mysql:8.0
    container_name: mysql3
    hostname: 172.28.41.59
    ports:
      - "3336:3336"
      - "33360:33060"
      - "33361:33061"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
      MYSQL_DATABASE: appdb
    # volumes:
    #   - ./mysql3.cnf:/etc/mysql/conf.d/custom.cnf:ro
    command: >
      --port=3336
      --server-id=3
      --report_host=172.28.41.59
      --report_port=3336
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
      --master-info-repository=TABLE
      --relay-log-info-repository=TABLE
      --binlog-checksum=NONE
      --log-slave-updates=ON
      --log-bin=binlog
      --transaction-write-set-extraction=XXHASH64
      --binlog-transaction-dependency-tracking=WRITESET
      --loose-group-replication-group-name="aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
      --loose-group-replication-start-on-boot=off
      --loose-group-replication-local-address="0.0.0.0:33361"
      --loose-group-replication-group-seeds="172.28.41.59:33161,172.28.41.59:33261,172.28.41.59:33361"
      --loose-group-replication-bootstrap-group=off
    restart: always
    extra_hosts:
      - "mysql1:172.28.41.59"
      - "mysql2:172.28.41.59"
      - "mysql3:172.28.41.59"

  mysql3-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql3-exporter
    depends_on:
      - mysql3
    environment:
      DATA_SOURCE_NAME: "root:root@tcp(mysql3:3306)/"
    command:
      - --config.my-cnf=/etc/mysql/.my.cnf
      - --mysqld.address=mysql3:3306
      - --mysqld.username=root
    volumes:
      - ../mysql-exporter-config/.my.cnf:/etc/mysql/.my.cnf:ro
    ports:
      - "9134:9104"
    restart: always

